### ISSUE TITLE
Attempting to create service object for a second time leads to an indefinity hang

### ISSUE THREAD

**Issue by XapaJIaMnu** [browsermt/bergamot-translator#100]
So, consider the situation when we want to reload the model, without quiting the application, as described here:

https://github.com/browsermt/bergamot-translator/blob/d7f6770dcee055ca1329ec4f0872e4d973fa7197/app/service-cli.reset.cpp#L17

(Perhaps the user wants to change the language?). At the moment the second time you initialise the model you would hang indefinitely here: 

https://github.com/browsermt/bergamot-translator/blob/d7f6770dcee055ca1329ec4f0872e4d973fa7197/src/translator/MarianInterface.cpp#L21

Any ideas, @jerinphilip @kpu ?

**Comment by jerinphilip** [comment]
a) Can you shed light on why this would hang? I'm noob and missing marian-docs. Had I been given full information (docs) I'd compile whatever minimum options are required and construct the options object from that with entries being explicit. 
b) Can't you hold options and reinit with Options (avoiding parsing again or worrying about)? Why are we looking at parsing for `Options` again, this looks like hopping through an unnecessary step? Either have flyweights keyed on `model_identifier` (maybe a lang direction or hash of options as YAML) or have `reinit(new Options)` on Service instance?

**Comment by XapaJIaMnu** [comment]
@jerinphilip 
a) No idea why it hangs, it just does

b) I am creating a new Options Object every time, I'm not just reparsing. I used the same file to illustrate the point, but in practise we might want to load a model that has completely different parameters (shapes, threads, scoring methods, vocabs...) https://github.com/browsermt/bergamot-translator/blob/d7f6770dcee055ca1329ec4f0872e4d973fa7197/src/translator/MarianInterface.cpp#L27

**Comment by XapaJIaMnu** [comment]
It seems to be deadlocking inside spdlog...

**Comment by XapaJIaMnu** [comment]
Yepp, we're never shutting down the loggers. A config parser would attempt to create a new logger. Even if we avoid the config parser, the service would also require a logger.

**Comment by jerinphilip** [comment]
https://stackoverflow.com/questions/37356743/how-to-start-and-shutdown-spdlog-multiple-times-in-the-same-program looks like what we should go for? 

It's the `general` logger that has to be shutdown: https://github.com/marian-nmt/marian-dev/blob/bb6092da2b89c3882aa256480cef13081fd6f50f/src/common/logging.h#L50;

**Comment by XapaJIaMnu** [comment]
Changing the code to have to spdlog drops makes the code work

```
 MarianInterface * mymodel = new MarianInterface("/mnt/Storage/students/esen/enes.student.tiny11/config.intgemm8bitalpha.yml");
  std::cerr << mymodel->translate("Test") << std::endl;
  spdlog::drop("general");
  spdlog::drop("valid");
  delete mymodel;
  mymodel = new MarianInterface("/mnt/Storage/students/esen/enes.student.tiny11/config.intgemm8bitalpha.yml");
  std::cerr << mymodel->translate("Test two") << std::endl;
  delete mymodel;
```

**Comment by XapaJIaMnu** [comment]
This is a nasty one to fix, because if you use smart pointers and do something like
```
std::unique_ptr<Service> service_(std::make_unique<Service>(Service()));
service_.reset(New Service()); // We have a crash, because service is created first before the old one is deleted.
```
Even attaching `spdlog::drop` to the destructor won't be enough.

**Comment by jerinphilip** [comment]
Shouldn't be as hard if we restructure properly, correct? Only loggers are causing problems. Have loggers created in Service instead of using marian's own  - some redundancy with https://github.com/marian-nmt/marian-dev/blob/bb6092da2b89c3882aa256480cef13081fd6f50f/src/common/logging.h) but okay. Maybe pass from outside even. 

I'm guessing if you have plans to swap-in swap-out models / yamls in memory you're looking at flyweights. So logger bound to the hash of the YAML and passed into service. Default logger to none. Change LOG instances to use this logger. Service/MarianInterface owns the logger. Later objects get a reference to the logger.

**Comment by XapaJIaMnu** [comment]
I don't like this solution. The logger is part of the marian library we shouldn't be replicating that functionality or fixing it outside of marian...

I can imagine some static variable that gets checked when creating a new logger and cleanly releases any old ones inside marian..
