### ISSUE TITLE
Empty sentence ("") crashes service-cli 

### ISSUE THREAD

**Issue by XapaJIaMnu** [browsermt/bergamot-translator#101]
Trying to translate an empty string results in a crash. Eg:

```bash
echo "" | ./service-cli -c /mnt/Storage/students/esen/enes.student.tiny11/config.intgemm8bitalpha.yml --mini-batch-words 2000
```
Results in
```
[2021-04-16 12:57:08] Error: Unhandled exception of type 'St12future_error': std::future_error: Broken promise
[2021-04-16 12:57:08] Error: Aborted from void unhandledException() in /mnt/Storage/bergamot-translator/3rd_party/marian-dev/src/common/logging.cpp:113
```

**Comment by jerinphilip** [comment]
What do we want to do here? I think I can add `Response::EmptyResponse` named constructor and an additional flag, setting the flag to true (false by default). It can be on the callee to check if the `Response` is empty.

There are two places:
1. Validate `Request`: If invalid, set to `EmptyResponse`. 
2. Validate `Histories`: If translations are invalid set to `EmptyResponse`.

I believe both are to some extent unhandled at the moment. Do we have any more corner cases to cover than the above?

**Comment by XapaJIaMnu** [comment]
As a caller of translate I expect that if I give an input I'd always be able to get an output. Empty string is a valid output.
As for Histories , can they not just be left empty?

**Comment by jerinphilip** [comment]
As of now only a worker from another thread can fire the completeRequest, which in turn builds response and sets the promise. I am guessing we're working with empty -> empty as a valid response.

For empty sentence alone, I intend to call a completeRequest (on construction, in the thread the request is queued) if the source-sentences are empty setting the corresponding response values to empty equivalent as well. This will happen behind #80, as it edits and adjusts this process.
