### ISSUE TITLE
Does not compile on windows megathread

### ISSUE THREAD

**Issue by XapaJIaMnu** [browsermt/bergamot-translator#105]
Hi @kpu @jerinphilip,

Here I'll list the specific issues that prevent the codebase from compiling on Windows and discuss/propose/implement workarounds.

1) https://github.com/browsermt/bergamot-translator/blob/c00c263f8f8e1eb02ecbac3c59acdbe591f4fe0a/src/translator/multifactor_priority.h#L6 `<sys/time.h>` is a unix header, not available on win32. This doesn't seem to be used anywhere, should we delete the `multifactor_priority.*` files?
2) https://github.com/browsermt/bergamot-translator/blob/c00c263f8f8e1eb02ecbac3c59acdbe591f4fe0a/src/translator/sentence_ranges.cpp#L35 and a few other places in the file. MSVC compiler doesn't like syntax like:  `(ByteRange){START, END};` and triggers the `C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax`. This looks like a warning, is it safe to ignore? Can we use alternative syntax?
3) https://github.com/browsermt/bergamot-translator/blob/c00c263f8f8e1eb02ecbac3c59acdbe591f4fe0a/src/translator/response.h#L63 MSVC doesn't like this, not sure why. `C2280 'marian::bergamot::Response &marian::bergamot::Response::operator =(const marian::bergamot::Response &)': attempting to reference a deleted function`
4) https://github.com/browsermt/bergamot-translator/blob/c00c263f8f8e1eb02ecbac3c59acdbe591f4fe0a/src/translator/response.cpp#L68 similar to 2), including also line 78 in the same file.
5) https://github.com/browsermt/bergamot-translator/blob/c00c263f8f8e1eb02ecbac3c59acdbe591f4fe0a/src/translator/pcqueue.h#L20 this is not so much of an issue, as much as it is wishful thinking. Getting boost on windows is a bit annoying, is it possible to replace this with some lightweight header like: https://github.com/DanielTillett/Simple-Windows-Posix-Semaphore ? If not, i guess we should add this to the `cmake` dependencies because currently we don't look for boost.

**Comment by jerinphilip** [comment]
1. That whole file can be deleted for now.
2. I'm using an old shorthand I know from C, it's just initing a strict. Can change it to something MSVC won't complain about.
3. Need more context here. I delete it to make it only Movable (I've found several instances where I accidentally copy it and incur a heavy cost otherwise). The class is in theory Copyable as of now since we removed string-view dependencies. I'd prefer to solve this by correcting where the compiler shows where we're copying instead of moving.
4. Can change. Same as 2.
5. We can swap this out for any producer consumer queue that's more multiplatform. Or fix this one for Windows in the way you prefer.

**Comment by XapaJIaMnu** [comment]
2 3 and 4 are warnings, they might be safely ignored, although, I'd prefer if we could fix 2, 3 other than adding an exception to msvc warnings. We can disable them with something like
```cpp
// Disable warning messages 4576.
#pragma warning( disable : 4576 )
```
As for 5, the problem is that we don't have `if (WIN32) findBOOST Required` is our `CMakeLists.txt` if we are to keep this. I'm not sure what other PCQueues are out there.

**Comment by kpu** [comment]
I'll take a stab at semaphore.

**Comment by XapaJIaMnu** [comment]
@jerinphilip just realised the 2, you want to remove the cast brackets for the more canonical c++ syntax.

**Comment by XapaJIaMnu** [comment]
Ok, so I nearly got it to compile. The last remaining issue that I am not really sure how to fix Response and Request. They are affected by this MSVC bug:

https://developercommunity.visualstudio.com/t/stdfuture-and-stdshared-future-require-t-to-have-d/1122412
https://developercommunity2.visualstudio.com/t/std::asyncs-std::future-doesnt-support/123622
https://developercommunity.visualstudio.com/t/stdasyncs-stdfuture-doesnt-support-types-that-are/123622

I think the solution on Windows would be to remove the move constructor and let them copy for now... @kpu  ?

This compiles 99%:

```patch
diff --git a/src/translator/response.cpp b/src/translator/response.cpp
index e5bc38f..1b9d0eb 100644
--- a/src/translator/response.cpp
+++ b/src/translator/response.cpp
@@ -10,7 +10,7 @@ namespace bergamot {
 
 Response::Response(AnnotatedText &&source, Histories &&histories,
                    std::vector<Ptr<Vocab const>> &vocabs)
-    : source(std::move(source)) {
+    : source(source) {
   // Reserving length at least as much as source_ seems like a reasonable thing
   // to do to avoid reallocations.
   target.text.reserve(source.text.size());
@@ -65,7 +65,7 @@ Response::Response(AnnotatedText &&source, Histories &&histories,
 
     Alignment unified_alignment;
     for (auto &p : hardAlignment) {
-      unified_alignment.emplace_back((Point){p.srcPos, p.tgtPos, p.prob});
+      unified_alignment.emplace_back(Point{p.srcPos, p.tgtPos, p.prob});
     }
 
     alignments.push_back(std::move(unified_alignment));
@@ -75,7 +75,7 @@ Response::Response(AnnotatedText &&source, Histories &&histories,
     auto normalizedPathScore = std::get<2>(result);
     auto wordQualities = hyp->tracebackWordScores();
     wordQualities.pop_back();
-    qualityScores.push_back((Quality){normalizedPathScore, wordQualities});
+    qualityScores.push_back(Quality{normalizedPathScore, wordQualities});
   }
 
   // Once we have the indices in translation (which might be resized a few
diff --git a/src/translator/response.h b/src/translator/response.h
index 4f87b8d..b610c75 100644
--- a/src/translator/response.h
+++ b/src/translator/response.h
@@ -46,21 +46,22 @@ public:
   ///
   Response(AnnotatedText &&source, Histories &&histories,
            std::vector<Ptr<Vocab const>> &vocabs);
+  Response() {};
 
   /// \cond HIDDEN_PUBLIC
   // Move constructor.
-  Response(Response &&other)
-      : source(std::move(other.source)), target(std::move(other.target)),
-        alignments(std::move(other.alignments)),
-        qualityScores(std::move(other.qualityScores)){};
+  //Response(Response &&other)
+  //    : source(std::move(other.source)), target(std::move(other.target)),
+  //      alignments(std::move(other.alignments)),
+  //      qualityScores(std::move(other.qualityScores)){};
 
   // The following copy bans are not stricitly required anymore since Annotation
   // is composed of the ByteRange primitive (which was previously string_view
   // and required to be bound to string), but makes movement efficient by
   // banning these letting compiler complain about copies.
 
-  Response(const Response &) = delete;
-  Response &operator=(const Response &) = delete;
+  //Response(const Response &) = delete;
+  //Response &operator=(const Response &) = delete;
 
   /// \endcond
 
diff --git a/src/translator/sentence_ranges.cpp b/src/translator/sentence_ranges.cpp
index aae9dd3..103576b 100644
--- a/src/translator/sentence_ranges.cpp
+++ b/src/translator/sentence_ranges.cpp
@@ -32,11 +32,11 @@ ByteRange Annotation::sentence(size_t sentenceIdx) const {
     // the flatByteRange and non-empty sentence before this happened and
     // construct empty string-view equivalent ByteRange.
     ByteRange eos = flatByteRanges_[eosId - 1];
-    sentenceByteRange = (ByteRange){eos.end, eos.end};
+    sentenceByteRange = ByteRange{eos.end, eos.end};
   } else {
     ByteRange bos = flatByteRanges_[bosId];
     ByteRange eos = flatByteRanges_[eosId - 1];
-    sentenceByteRange = (ByteRange){bos.begin, eos.end};
+    sentenceByteRange = ByteRange{bos.begin, eos.end};
   }
   return sentenceByteRange;
 }
@@ -65,7 +65,7 @@ void AnnotatedText::addSentence(std::vector<string_view>::iterator begin,
   std::vector<ByteRange> sentence;
   for (auto p = begin; p != end; p++) {
     size_t begin_offset = p->data() - &text[0];
-    sentence.push_back((ByteRange){begin_offset, begin_offset + p->size()});
+    sentence.push_back(ByteRange{begin_offset, begin_offset + p->size()});
   }
   annotation.addSentence(sentence);
 };
diff --git a/src/translator/sentence_ranges.h b/src/translator/sentence_ranges.h
index b3986e3..42a2fcd 100644
--- a/src/translator/sentence_ranges.h
+++ b/src/translator/sentence_ranges.h
@@ -125,9 +125,9 @@ public:
   /// constructor is disallowed).
   AnnotatedText(std::string &&text) : text(std::move(text)){};
 
-  AnnotatedText(AnnotatedText &&annotatedBlob)
-      : text(std::move(annotatedBlob.text)),
-        annotation(std::move(annotatedBlob.annotation)) {}
+  //AnnotatedText(AnnotatedText &&annotatedBlob)
+  //    : text(std::move(annotatedBlob.text)),
+  //      annotation(std::move(annotatedBlob.annotation)) {}
 
   /// Returns the number of sentences in the annotation structure.
   const size_t numSentences() const { return annotation.numSentences(); }
```

There are some issues with built-in pcre2 (The libraries have a phantom "d" before the end, such as `pcre2.8-posixd.lib` but the one from vcpkg works fine) and openblas from vcpkg (but MKL works fine supposedly.)

**Comment by jerinphilip** [comment]
> The last remaining issue that I am not really sure how to fix Response and Request

`Response` is copy-constructible. There is a comment over there (the deletion of constructors) saying it can be removed.

I'm not sure about `Request` you're talking about. Can you elaborate? The 5 points you listed doesn't have anything related to `Request`. Are you talking perhaps about `AnnotatedText`? That's also copy-constructible.

**Comment by XapaJIaMnu** [comment]
Yeah, Response and AnnotatedText. The issue reports itself in a file named `request.h`

Regardless, these are the changes necessary compilation until MSVC gets fixed which will be... Some time. 
Removing the delete constructors wouldn't help, because MSVC implicitly deletes those when there is a custom move implementation.

**Comment by jerinphilip** [comment]
@XapaJIaMnu: Any idea why the following offends MSVC? Or is this a debugging artifact?

```diff
 Response::Response(AnnotatedText &&source, Histories &&histories,
                    std::vector<Ptr<Vocab const>> &vocabs)
-    : source(std::move(source)) {
+    : source(source) {
```

**Comment by XapaJIaMnu** [comment]
I haven't ab tested it, it might not be necessary. (or debugging artefact)

**Comment by XapaJIaMnu** [comment]
Fixed
