### ISSUE TITLE
Allocation of 8x of actual memory required happening for byte based file loading

### ISSUE THREAD

**Issue by abhi-agg** [browsermt/bergamot-translator#110]
[AlignedMemory](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/definitions.h#L26) class, which is being used to pass [model and shortlist file as byte streams](https://github.com/browsermt/bergamot-translator/blob/main/src/TranslationModel.h#L38-L39), is allocating 8 times of the actual memory required.

This is happening because [size * sizeof(T)](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/aligned.h#L23) will amount to `size * 8` (or `size * 4` on 32-bit machines) when `T` is a pointer type (`const void*` in this case). This behavior can easily be seen by running [byte-array apps](https://github.com/browsermt/bergamot-translator/tree/main/app).

API user knows the size of these files in bytes. Allocating [size * sizeof(T)](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/aligned.h#L23) bytes internally:
1. Forces user to perform a pre-processing step if 8x memory allocation has to be avoided
    (i.e. call [AlignedVector constructor](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/aligned.h#L17) with `size = file_size_in_bytes/sizeof(const void*)`)
2. Forces user to know the size of the template parameter (i.e. `sizeof(const void*)` in this case) which is different for 32-bit and 64-bit machines.

The consumer of the API should not be burdened with both of these things (especially the 2nd one). All that an API consumer should provide is the size of the files in bytes (the same way that is happening in [loadFileToMemory](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/byte_array_util.cpp#L82-L85) function)

One solution to fix this problem is to simply change:

`typedef AlignedVector<const void*> AlignedMemory;`

to

`typedef AlignedVector<unsigned char> AlignedMemory;`

@kpu @XapaJIaMnu If you agree to this proposal, I will submit a change asap as it is blocking me to make progress on [this issue](https://github.com/browsermt/bergamot-translator/issues/75). I am also open for other suggestions to fix this issue 👍 

cc @andrenatal @jerinphilip

**Comment by kpu** [comment]
You're right it should be char (to be pedantic not unsigned char)

**Comment by abhi-agg** [comment]
I will submit a PR for this then. Thanks for a super quick response 👍

For clarity, the following is what you recommend. Right?

`typedef AlignedVector<char> AlignedMemory;`

**Comment by kpu** [comment]
Yes
