### ISSUE TITLE
Parsing config string into Options invokes config validator for byte array based constructor

### ISSUE THREAD

**Issue by abhi-agg** [browsermt/bergamot-translator#112]
Currently, the [constructor of the Service class](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L54-L55) invokes [parseOptions](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L56).

The [parseOptions](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/parser.h#L34-L65) function performs 2 responsibilities right now:

1. It parses the `config` string to `marian::Options` object (which it should do because Marian works with this object internally almost everywhere)
2. And runs the [ConfigValidator](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/parser.h#L61-L62) on the parsed `marian::Options` object to check its validity

My question is pertaining to its 2nd responsibility: Should the [ConfigValidator](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/parser.h#L61-L62) step be executed at all while [constructing Service](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L54-L55) with model, shortlist (and vocab in future) files as bytes?

I believe we don't need the validation step for this constructor because [ConfigValidator for translation mode](https://github.com/browsermt/marian-dev/blob/master/src/common/config_validator.cpp#L49-L66) checks:
1. Whether model file and vocab files are provided and
2. The path of these files are valid.

We don't need these checks if we are providing these files as bytes.

**My proposal is**: Since the [constructor](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L54-L55) is designed for the cases when model, shortlist file (and vocab in future) can be provided as byte array, we can remove the validator step from it (of course, it would mean [no optional arguments](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L55) in this constructor but I can make that change in the PR for the issue https://github.com/browsermt/bergamot-translator/issues/75).

@kpu @XapaJIaMnu @jerinphilip I can provide this fix if the proposal sounds good to you. Please let me know if I missed something here 👍 
cc @andrenatal

PS: I ran into this issue while providing model files as bytes from JS side. I removed the model file in `config` parameter of this constructor (because I am providing model file as bytes) and the engine started failing at ConfigValidator step (because it expects model file in the `config` parameter). Also, this validation step is not executed for the [other 2 constructors](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L44-L46) of the same class.

**Comment by jerinphilip** [comment]
> I believe we don't need the validation step for this constructor

If it's just to save runtime can we have a `validate=true` default argument to parseOptions? I'd like service-cli etc to validate to have sane error outputs. The constructor meanwhile can call parseOptions without validation? 

Are there any compile-time issues at the moment?

**Comment by jerinphilip** [comment]
>  am wondering how would you use this validation in service-cli if the only constructor that calls this validation step is the constructor with ByteArrayLoads

This is thus because I'm reading args from commandline and configparser converts it directly into options. It looks like we'll need this `parseOptions` function, when the cmdline simplifies to `-c config.yml` or `-i binary-to-rule-them-all` (https://github.com/browsermt/bergamot-translator/issues/104#issue-861311748).

> it would mean no optional arguments in this constructor but I can make that change in the PR for the issue

This means WASM is losing the capability to load from file-system, as you're doing now. I understand they ByteArray loads are preferred, but are you sure you want to lose the fallback checks?

**Comment by abhi-agg** [comment]
> > am wondering how would you use this validation in service-cli if the only constructor that calls this validation step is the constructor with ByteArrayLoads
> 
> This is thus because I'm reading args from commandline and configparser converts it directly into options. It looks like we'll need this `parseOptions` function, when the cmdline simplifies to `-c config.yml` or `-i binary-to-rule-them-all` ([#104 (comment)](https://github.com/browsermt/bergamot-translator/issues/104#issue-861311748)).
> 

Got it 👍 

> > it would mean no optional arguments in this constructor but I can make that change in the PR for the issue
> 
> This means WASM is losing the capability to load from file-system, as you're doing now. I understand they ByteArray loads are preferred, but are you sure you want to lose the fallback checks?

Yes. We would always want to load by byte arrays. If we fall back to load from file-system, we can add another API that just accept config string and there we can keep the validation check.

**Comment by XapaJIaMnu** [comment]
We definitely want to keep the old behaviour as an option, as we don't want to lose the ability to pass non-byte-array models so that we maintain binary compatibility with marian-dev-master. WASM on the other hand has a specific usecase where files can't be easily accessed from the disk, so they need to be provided as a byte array. The proper solution is to no validate the paths of anything that is provided as a byte array, however as validator is part the marian source, that would require modifications in the 3rd party module which is less than ideal, but doable.

The other solution is what @abhi-agg  mentioned and just not require validator when parsing by byte array. Since config validator only validates paths: https://github.com/browsermt/marian-dev/blob/a2e3dca82d3fbf534cecdec1b75d84c39ba77092/src/common/config_validator.cpp#L48

And whether the devices and file extensions are valid, we can safely exclude it when we're providing byte array stuff. We have other mechanisms of validation for those in place anyways.

**Comment by abhi-agg** [comment]
> We definitely want to keep the old behaviour as an option, as we don't want to lose the ability to pass non-byte-array models so that we maintain binary compatibility with marian-dev-master. WASM on the other hand has a specific usecase where files can't be easily accessed from the disk, so they need to be provided as a byte array. The proper solution is to no validate the paths of anything that is provided as a byte array, however as validator is part the marian source, that would require modifications in the 3rd party module which is less than ideal, but doable.
> 
> The other solution is what @abhi-agg mentioned and just not require validator when parsing by byte array. Since config validator only validates paths: https://github.com/browsermt/marian-dev/blob/a2e3dca82d3fbf534cecdec1b75d84c39ba77092/src/common/config_validator.cpp#L48
> 

@XapaJIaMnu  The solution that I proposed will also allow us to maintain the old behavior because we have [another constructor](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L75) that work with file based loading 👍 

> And whether the devices and file extensions are valid, we can safely exclude it when we're providing byte array stuff. We have other mechanisms of validation for those in place anyways.

Great. So, I can add a `validate` boolean parameter to `parseOptions` function and call it with `validate=false` from the byte loading based constructor. I will implement this fix and submit a PR.
