### ISSUE TITLE
Validating AlignedMemory passed via Service constructor

### ISSUE THREAD

**Issue by abhi-agg** [browsermt/bergamot-translator#113]
Please correct me if I am wrong but currently the [Service constructor that uses bytes for files](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L54-L55) doesn't perform:
1. Validation of the shortlist bytes
2. Validation of the model bytes

The [validation code](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/byte_array_util.cpp#L30) is already present in the repo but is being invoked only in the [apps](https://github.com/browsermt/bergamot-translator/blob/main/app/service-cli-bytearray.cpp#L19-L20).

@kpu @XapaJIaMnu @jerinphilip In my opinion, this validation should also be invoked from within the [Service constructor that uses bytes for files](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L54-L55).
cc @andrenatal

**Comment by jerinphilip** [comment]
> check increases shortlist loading time because it has to go over all indices and check they are in range. I specifically asked for it to be optional. And honestly it should be. Mozilla can later go in and check once if they want to, and care about loading time, which they seem to.
>
> I think of the check here as more for untrusted input.


https://github.com/browsermt/bergamot-translator/pull/69#discussion_r600544180

**Comment by XapaJIaMnu** [comment]
The binary model validation code is cheaper than the shortlist one. Can you measure its footprint in WASM just in case, before we commit to running it every time?

**Comment by abhi-agg** [comment]
The comment https://github.com/browsermt/bergamot-translator/pull/69#discussion_r600544180 and what @XapaJIaMnu wrote

> The binary model validation code is cheaper than the shortlist one.

explains to me why we are not doing validation for shortlist file.

But, I am confused regarding the default behavior as per https://github.com/browsermt/bergamot-translator/pull/69#discussion_r600544180 and https://github.com/browsermt/bergamot-translator/pull/69#discussion_r600550911.

1. What I understood is that **by default**, the validation of both shortlist and model bytes is **NOT** happening when [instantiating Service class with byte loading constructor](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L84-L86). Right?

> Mozilla can later go in and check once if they want to

2. If `1` is correct, then the how to perform this check once?

Looping in @qianqianzhu as she is the implementer 👍

**Comment by jerinphilip** [comment]
iirc, there's a flag in options which checks, called `--check-bytearray`. This can also equivalently be enabled through the YAML. It checks the model / shortlist for validity within the constructor (or so I hope). 

https://github.com/browsermt/bergamot-translator/blob/fa2003e70d0baf88a5db6f51086ff899c7192e63/src/translator/batch_translator.cpp#L25

The above seems to be only for shortlist at the moment. Model seem to be missing, which I think is best done by using the following under the same flag:

https://github.com/browsermt/bergamot-translator/blob/fa2003e70d0baf88a5db6f51086ff899c7192e63/src/translator/byte_array_util.cpp#L30

**Comment by qianqianzhu** [comment]
For 1, by default, the validation of bytes is `true` for both shortlist and model bytes.
As Jerin said above, the control of shortlist bytes validation is via `--check-bytearray`. The default is true.
The validation of the model bytes is always happening when loading from the file. We should also control this via `--check-bytearray` option. I will fix this during plumbing the vocab bytes.

**Comment by kpu** [comment]
Loading time is a big issue right now so it's important to bypass checks if we can.  In principle we'd like to support 3rd-party models, but want to make sure they can't segfault marian / disclose memory.  That means ensuring array indices are in range etc.  

The way I see it, you can download the model, call with --check-bytearray (or whatever) on the downloaded model, and then not do it the rest of the time.

**Comment by abhi-agg** [comment]
To summarize:

1. [Instantiating Service class](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L84-L86) by providing model and shortlist bytes performs byte validation by default.
2. I can disable shortlist byte validation by setting the option `--check-bytearray` to `false`
3. The capability to disable model byte validation currently doesn't exist but will be introduced soon via the same `--check-bytearray` option
4. Whenever a model is created for a language pair for the first time then this validation should happen but subsequent construction of the model for the same language pair should avoid this validation (for faster loading).

Thanks everyone for clarification 👍
