### ISSUE TITLE
Callback instead of future?

### ISSUE THREAD

**Issue by kpu** [browsermt/bergamot-translator#126]
In @XapaJIaMnu 's use case there's a UI thread.  Currently we have a future and waiting on that future means blocking, which means another thread whose sole purpose is to wait on the future then notify the UI thread.  This is a bit silly and could be fixed with a callback.  
Mozilla isn't using the future now anyway (that sentence sounds funny) and didn't care if it was a callback IIRC.  
So we may as well change it to a callback.

**Comment by XapaJIaMnu** [comment]
While we're at it, it'd be nice if the service could report somehow when it's ready to accept translations (cause currently marian may initialise far slower

**Comment by jerinphilip** [comment]
> While we're at it, it'd be nice if the service could report somehow when it's ready to accept translations (cause currently marian may initialise far slower

You pass a callback on ready works for you? I'm guessing you're signalling a UI thread about something and the function will have enough context captured? Default to no-op if nothing is supplied. `std::function<void(void)>`.
