### ISSUE TITLE
Refactor Service

### ISSUE THREAD

**Issue by qianqianzhu** [browsermt/bergamot-translator#133]
PR https://github.com/browsermt/bergamot-translator/pull/122 left some refactorings in `Service` to be done for better design (I will work on this issue):
  1. refactor `loadVocabularies()` and wrap `vector<Ptr<Vocab const>>` in a new container. So we can take `loadVocabularies()` out of `Service`. `loadVocabularies()` should not belong to `Service`.
  2. bundle all byte arrays in a new structure, like `MemoryBundle`.  As suggested by @jerinphilip:
  ```cpp
struct MemoryBundle {
	AlignedMemory model;
	AlignedMemory shortlist;
	std::vector<std::shared_ptr<AlignedMemory>> vocabs;
	AlignedMemory ssplitPrefixFile;
};
```
  3. refactor Service constructors to remove redundancies

2 and 3 will affect the WASM JS bindings. @abhi-agg need your input here. 

This issues is open for discussion, so feel free to leave any comments.

**Comment by abhi-agg** [comment]
>     2. bundle all byte arrays in a new structure, like `MemoryBundle`.  As suggested by @jerinphilip:
> ```c++
> struct MemoryBundle {
>   AlignedMemory model;
>   AlignedMemory shortlist;
>   std::vector<std::shared_ptr<AlignedMemory>> vocabs;
>   AlignedMemory ssplitPrefixFile;
> };
> ```

I am fine with this.

>     3. refactor Service constructors to remove redundancies

In my opinion:

1. All the constructors using `Options` can be made private (as we didn't want to expose marian internals in public APIs) unless there is a good reason to keep them public. @jerinphilip might have something to add here.

2. For each category of constructors (i.e `Options` based and [string](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/service.h#L97) based), we should have 2 separate constructors: one for loading only by bytes and another . Something like this below:
    1. One that loads only by files. e.g. `Service(const std::string &config)`
        1. It will call `parseOptions(config, /*validate=*/true)` because we would want to validate the model and vocab file names etc.
    2. Another that loads only by bytes. e.g. `Service(const std::string &config, MemoryBundle memoryBundle)`
        1. It will call `parseOptions(config, /*validate=*/false)`

**Comment by jerinphilip** [comment]
> 1. All the constructors using Options can be made private... unless there is a good reason to keep them public

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#example-bad-4. If I were to do this, I get `Options` upon commandline parsing, I'm not doing n rounds of conversions again = good enough-reason. I get 2 constructors here thus.

**Comment by qianqianzhu** [comment]
Close as resolved.
