### ISSUE TITLE
Version file generation is done in the src tree

### ISSUE THREAD

**Issue by XapaJIaMnu** [browsermt/bergamot-translator#161]
@abhi-agg it is bad practise to have cmake generate files in the source directory. If a file is generated after configure, it should be in `${CMAKE_BINARY_DIR}`, not in `src/translator/project_version.h`.

At the very least, you can add a `.gitignore` entry for it so that this file is not accidentally picked up by someone working on the project.

I have not fixed this myself, as other projects also read this file, and I am not sure where exactly things need to be updated.

**Comment by kpu** [comment]
Agreed, generated files go in the binary directory.
