### ISSUE TITLE
Create native (no-wasm) packages for Debian

### ISSUE THREAD

**Issue by KOLANICH** [browsermt/bergamot-translator#174]
And promote them to the official repos

**Comment by XapaJIaMnu** [comment]
This can easily be done with CPACK. Here is the necessary CMakeLists.txt change:
https://github.com/XapaJIaMnu/translateLocally/blob/b24679339bac1f768f6bf0f283774500d0f438d9/CMakeLists.txt#L180
А bigger problem however is that we're currently compiling with `march=native` which would make packages which are highly machine dependent.

**Comment by KOLANICH** [comment]
>А bigger problem however is that we're currently compiling with march=native

Cannot it be redefined with CMake command line?

**Comment by XapaJIaMnu** [comment]
We need to modify it in several places, down the subprojects. Not too difficult, just someone needs to do it xD

**Comment by kpu** [comment]
https://translatelocally.com/release/translateLocally-v0.0.1+ae858d1-Ubuntu-20.04.avx2.deb

**Comment by kpu** [comment]
I guess "promote them to the official repos" is still open...
