### ISSUE TITLE
First class pivot translation capability

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#212]
https://github.com/mozilla/bergamot-translator/issues/62 is an ask for a "pivoting" through English to obtain non-English translations feature between languages `xx` and `yy`. 

```
[xx-source] -> [en-intermediate] -> [yy-target]
```

Just thinking out loud here, to initiate discussion. Implementation will take a while and will have to wait for #210. A relevant feature is support for parameterisation by the model in methods in `Service`, being tracked in #209 and implementation ongoing in #210 as part of supporting multiple models. Using multiple models through JS API provided by #210 alone will lead to subpar performance and incomplete outputs (the pivot feature is already 2x slower, comm back and forth will make it worse).  

Instead, we can support provision of the following additional method which sequences the underlying computations from a list of models supplied externally from JS. A loose API sketch below:

```cpp
class Service {
public:
// Applies models in series to translate source to target.
// Models[ [x_1 -> x_2] - [x_ 2-> x_3] ... [x_{n-1} -> x_{n}] ] = Model[x_1 -> x_n]
void sequencedTranslate(
	std::vector<std::shared_ptr<TranslationModel>> models, // < models to be applied in series
	std::string &&source, 
	CallbackType clientCallback,
	const ResponseOptions responseOptions) {
	// Reduce application of pivotHalfTranslate(...) on models 
	
	// Reduce needs to happen with chained-callbacks, because we don't 
	// immediately know when a request finishes.
	
	// (n-1)th Response.target is the n-th Response.source (for consistent tokenizations)
	
	// Response.alignment matrix aggregations are binary op, matrix multiplied(?)
	// over each pair of pivotHalfTranslate ops.
}

private:	

void pivotHalfTranslate(
	std::shared_ptr<TranslationModel> xx_to_yy, 
	AnnotatedText source, // need to supply consistent sentence/tokens at intermediates as source, target
	CallbackType callback,
	const ResponseOptions responseOptions,
);

}
```

`models.size()` times slower for a lower bound, additional overheads of matrix-multiplies, greater error guaranteed. On the bright side... still better than no `xx->yy` translation, I guess. 

* The sentences need to align one to one from source to intermediates to target. 
* The tokens need to match from source to intermediate to target. This is to avoid dimension mismatches when multiplying adjacency matrices between (`xx->yy`) (`yy->zz`). Tokenizing `yy` independently at source and target can lead to different tokenizations. Errors will add on each multiplication of matrices, TagTree is crippled. I think the reduction may not be as trivial as a matrix-multiply, might need to work this out in detail. In any case, we still need consistent intermediate sentence-splitting and tokenization. 
* WASM will need to expose `sequencedTranslate` (or its blocking counterpart).

**Comment by kpu** [comment]
Ugh, we currently have separate vocabularies for each language pair.  So they will be differently tokenized.  So we can't just multiply the alignment matrices to project.  

Potential heuristic for alignment.  Inject a third matrix in between, based byte (or character) weighted averaging.  Let's say we are translating fr->en->es.  
Translating fr->en gives me alignment matrix p(fr token | en token in fr-en vocab).  We can copy this to the byte level p(fr token | en byte).  Then p(fr token | en token in en-es vocab) = avg_{byte b in en token in en-es vocab} p(fr token | en byte b).  
Translating en->es gives me an alignment matrix p(en token in en-es vocab | es token).  


We could impose the same English (or in general pivot language) vocabulary.  Models would have to be rebuilt which we should probably be doing anyway.  We'd lose tied embeddings and the models would get bigger though Jerin points out we could halve the vocabulary maybe?

**Comment by jerinphilip** [comment]
Okay, new problem or not? Translating from A -> B -> C, assuming a 128 token wrap, 1024 batch size. 

Now a corner case, we have a 128 token input (A), which gets translated to a >128 token output (B). We try to feed the AnnotatedText at (B) into the batching pipeline again, but without rewrap to 128. Since we're bucketing by length and only have buckets till 128, > 128 is segfault. 

Ideas:

1. Rewrap. All hell breaks loose in sentence correspondence? We now have to ensure a source sentence (A) maps to a target sentence (C). Do we simply collect and reduce to a single-sentence? There are no bucket segfaults at Response "collection", so should be okay.
2. Use max-length factor 1.0 or something, so we don't exceed tokens at translation-queries? Is this even feasible? This also assumes language-specific vocab, we can't control this at separate vocabs.

**Comment by jerinphilip** [comment]
Update on the status of this feature:

https://github.com/jerinphilip/bergamot-translator/pull/28 brings pivoting PR (#236) up-to-date with main. Only `AsyncService` has pivoting successfully implemented as of now and is currently used in conjunction with HTML to translate from English to English via Estonian with a demonstration in the below screenshot.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/727292/147771014-dc2f9e1f-b3ee-41c5-913a-9e61d5ceab7c.png">

The document structure appears mostly intact. If looked closely, "Applied Physics" somehow became "Appropriate Physics" 😄 . 

(The branch with the webapp used for demonstration is at https://github.com/jerinphilip/tagtransfer/pull/2).

There are a few concerns/grievances with HTML as I move forward with replicating the functionality for `BlockingService`, which I'll be adding to this thread or opening new issues for shortly.

**Comment by jerinphilip** [comment]
Now in main through #236.
