### ISSUE TITLE
Python bindings and a module

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#234]
It's easier to adopt for a wider audience if we can provision python bindings. I have in the past for https://github.com/browsermt/bergamot-translator/issues/185#issuecomment-868432213 built python bindings using pybind11 and used them successfully in experiments. While I was planning to retire this due to EBR getting in the way from #202, with #227 it's possible to retain pybindings now. 

### Existing Bindings

This is currently in https://github.com/jerinphilip/lemonade/blob/unstable/bindings/python/bergamot.cpp, needs to be updated to the recent re-architecting allowing multiple models. I have in the past ran into static-linking/dynamic-linking required for python issues which I had to solve by doing LD_PRELOADS everytime. Don't remember what the exact issues were but will be documented here soon.

These worked in the past and will need finessing:
* https://github.com/jerinphilip/bergamot-translator/blob/pybind11-exps/python-exps/Basic.ipynb
* https://github.com/jerinphilip/bergamot-translator/blob/pybind11-exps/python-exps/%3Cunk%3E%20analysis.ipynb

### Potential use-cases

1. There is a potential use-case for testing TagTree algorithm (#199) in the wild on HTML data making the HTML parsing easier and throwing all sorts of text in the wild at the algorithm. Python's default HTML parser seems to be able to provide the position of the tag in the text (https://docs.python.org/3/library/html.parser.html#html.parser.HTMLParser.getpos). With #233 (or even without temporarily) we can get this ready and try to maintain it as development progresses. The assert is construct TagTree from HTML parse of input, translate it and obtain TagTree for output. Construct target-html. Parse. If Parse claims invalid HTML we have failed, otherwise, we're good to go from an engineering standpoint. These are by no means a test for quality, but will be enough to see if any input can break the code and cause it to fail. Some of these can be converted after manual verification as test-cases to ensure no regressions for the TagTree feature. 
2. Dialect seems to be written in python and can potentially use the bindings if it can be used standalone. https://github.com/dialect-app/dialect/issues/183#issuecomment-946846328

Opening this issue to document progress.

**Comment by jelmervdl** [comment]
🎉🎉🎉 Thank you @jerinphilip for this this is going to make building experiments for the HTML processing bits so much easier!
