### ISSUE TITLE
Use optimized gemm implementation when available for wasm target

### ISSUE THREAD

**Issue by abhi-agg** [browsermt/bergamot-translator#264]
We want to be able to use the optimized gemm implementation when available in the environment, otherwise resort to using the portable fallback implementation of the [interface](https://github.com/browsermt/marian-dev/blob/master/src/tensors/cpu/wasm_intgemm_interface.h) for wasm target

**Comment by kpu** [comment]
Related https://github.com/browsermt/marian-dev/issues/63
