### ISSUE TITLE
Be careful with integers that can overflow

### ISSUE THREAD

**Issue by kpu** [browsermt/bergamot-translator#27]
There's a lot of `int` in here.  

https://github.com/browsermt/bergamot-translator/blob/45a8309c6972b121d62f1e9329267f752b8c796b/src/translator/request.h#L98-L150

1. We shouldn't need an integer batch id anyway, so best to get rid of it.  Poison can be something else, a bool even. Sequential IDs shouldn't be signed 32-bit integers.   
2. In general sizes can be > 4 billion if size_t permits.  Don't be sloppy with types here.  

As is, one could run 2^32-1 batches through then it would see poison and deadlock.

**Comment by abhi-agg** [comment]
Use of `size_t` can lead to failures on WASM. I left a comment in the commit to use a platform independent data type (say `uint64_t`).

**Comment by jerinphilip** [comment]
Keeping these platform dependent on the largest container size possible makes sense, no?

How about a `wasm_quirks.h` and typedef to turn of locks and mutexes and whatnot, also redefine size_t. Include with a compile wasm guard everywhere instead? This won't work?

**Comment by kpu** [comment]
I think `size_t` is preferable when it is the size of something.  If you start using it interchangeably with uint64_t or including it in a file then shame on you.

**Comment by kpu** [comment]
`size_t` isn't a WASM quirk per se.  It compiles in 32-bit mode.  Just use `size_t` properly.
