### ISSUE TITLE
Making ssplit-cpp self contained for bergamot project

### ISSUE THREAD

**Issue by abhi-agg** [browsermt/bergamot-translator#36]
Currently, users are required to have pcre2 library already installed on the system to be able to use ssplit-cpp in bergamot project. To be able to run it for wasm, we need the pcre2 library that is compiled for WASM and link it.

There are 2 ways to solve this issue:

1. Either link against a pcre2 library that is compiled for wasm (it is a bad way of intergrating)
2. Include pcre2 sources in ssplit-cpp in 3rd_party folder, build it and link it in ssplit-cpp as an alternative to linking with pre-installed pcre2 on system

2nd way is clearly more maintainable and clean solution.

I am ready to do this task and can submit a PR.
If @ugermann doesn't want to always compile pcre2 from sources then I am fine with that as well. I can add a cmake option `USE_INTERNAL_PCRE2` which can enable/disable building pcre2 from sources.

This is blocking my work and we need to agree fast.

**Comment by kpu** [comment]
If you're volunteering, I will agree with option 2.  

Also, actual question here: why is linking a bad way of integrating?  I mean we link with libc right?

**Comment by abhi-agg** [comment]
@kpu Option 2 done already [via this PR](https://github.com/ugermann/ssplit-cpp/pull/10). Just waiting for the merge.
@ugermann Can you please merge it?

**Comment by abhi-agg** [comment]
Closing this as https://github.com/browsermt/bergamot-translator/pull/45 is merged to main.
