### ISSUE TITLE
Single source file as an Application

### ISSUE THREAD

**Issue by abhi-agg** [browsermt/bergamot-translator#37]
Currently, there are 3 different files in [app folder](https://github.com/browsermt/bergamot-translator/tree/jp/absorb-batch-translator/app).

The app folder should contain only one file that demonstrates the use of unified APIs (which is done in [main.cpp](https://github.com/browsermt/bergamot-translator/blob/jp/absorb-batch-translator/app/main.cpp))

The other files should be removed once everything gets stabilized.

**Comment by jerinphilip** [comment]
I don't think this is closed, given GitHub CI and cache encourages single-application, I might end up adding a `--mode {decoder,bytearray,service-cli,...}` and a single cli. So :D

**Comment by abhi-agg** [comment]
Removing `wontfix` label from here then 👍
