### ISSUE TITLE
Importing bergamot for Python fails without network connection.

### ISSUE THREAD

**Issue by vgbundo** [browsermt/bergamot-translator#430]
In python "import bergamot" fails if a network connection to the internet is unavailable.  This occurs even if the model to be used is already available, such that it is not necessary to download anything to perform translation.

This occurs because TranslateLocallyLike.__init__() always calls TranslateLocallyLike.update() which attempts to fetch the latest "models.json" file from the internet.

**Comment by jerinphilip** [comment]
@vgbundo Thank you for the detailed report. I have pushed something which appears to be working for me locally. Let me know if this works for you. A wheel should be available at https://github.com/browsermt/bergamot-translator/releases/tag/latest. Might take a bit longer to hit PyPI.

The python package a voluntary contribution and could use support of the users. Please keep them reports coming for stuff you find during your usage, and feel free to take initiative to discuss possible improvements here and contribute towards the efforts.
