### ISSUE TITLE
WASM allows copy-construction on object explicitly disallowed by nature to copy-construct

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#47]
Currently in source due to @abhi-agg: "I had to hack something together for WASM to work", for which we now have sharable build error logs courtesy of https://github.com/browsermt/bergamot-translator/pull/46. 

I deem this an issue - whether hack or not, unless explained and got to the bottom of this is a point of potential error (we transfer this object through future) allowing copy-construction allows for garbled outputs, which is why this was explicitly disallowed. 

https://github.com/browsermt/bergamot-translator/blob/a9e0d800ae5ca2538b17921f9702de4f3306a738/src/TranslationResult.h#L23-L60

**Comment by kpu** [comment]
@abhi-agg That `operator=` implementation is incorrect and a segfault waiting to happen.  There is a very good reason it was disabled.  

The `string_view` objects are backed by the string.  You're making a copy of the string which then has its own memory and address.  But the `string_view` objects are copied raw still backed by the old string.

**Comment by jerinphilip** [comment]
TranslationResult is gone, so closing.
