### ISSUE TITLE
Model loading from byte buffer

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#50]
@XapaJIaMnu 

For model load I see modifications to [Service](https://github.com/browsermt/bergamot-translator/blob/f17f02a54431403956d1fa333f44d1144e66dd8f/src/translator/service_base.h) and [BatchTranslator](https://github.com/browsermt/bergamot-translator/blob/f17f02a54431403956d1fa333f44d1144e66dd8f/src/translator/batch_translator.h).  Service is currently subclassed as a [NonThreaded](https://github.com/browsermt/bergamot-translator/blob/f17f02a54431403956d1fa333f44d1144e66dd8f/src/translator/service_base.h#L45) implementation and a [multithreaded](https://github.com/browsermt/bergamot-translator/blob/f17f02a54431403956d1fa333f44d1144e66dd8f/src/translator/service.h#L18) one. Calls to initialize BatchTranslator happens in respective constructors.

The model loading happens actually in BatchTranslator.

https://github.com/browsermt/bergamot-translator/blob/f17f02a54431403956d1fa333f44d1144e66dd8f/src/translator/batch_translator.cpp#L26-L39

So I'll need createScorers (L32) from marian with a bytesbuffer which I pass all the way from whichever implementation of Service requires it. The concurrent-queuing implementation is a bit ahead and both messier and cleaner depending on places (imo), but I'm taking responsibility of bringing it to sync once you have integrated your changes in main.

**Comment by XapaJIaMnu** [comment]
So... I have been working off main and apparently that branch is very far from state-of-the art. Sadly.
If you check https://github.com/browsermt/bergamot-translator/tree/load_as_byte_arr this exposes the byte array loading all the way to the top. Which branch do I need to merge this with so that I can write an example code?

**Comment by jerinphilip** [comment]
> I hope we are doing something about the redundant abstraction. AbstractTranslationModel can be merged with TranslationModel. 

@abhi-agg wants multiple translators integration capability. My understanding is this means more than marian (maybe another CPP translator/whatever). Rename TranslationModel -> MarianIntegrationModel : AbstractTranslationModel and the existence could be justified, I guess.

> Which branch do I need to merge this with so that I can write an example code?

**Critical bit**: It is `main`. You're probably missing `-DUSE_WASM_COMPATIBLE_SOURCES=off` without which everything is turned off. bergamot-translator is running WASM default. I settled for the flag and the ability to switch modules to compile against full code in my development work.  Have a look at:
* [doc/marian-integration.md](https://github.com/browsermt/bergamot-translator/blob/main/doc/marian-integration.md)

> I also didn't understand the purpose of separate Service and ServiceBase 

ServiceBase has common elements between the single-threaded and multi-threaded versions. They're not really clean per se, and are getting adjusted to more meaningful abstractions in the concurrent-queueing branch (don't try to edit here, it's a work in progress). 

> ServiceBase and BatchTranslator

I put all of marian's translation code which I grabbed from mts in `BatchTranslator`. I'm not sure why you don't want them separately, I'd like to listen to the alternative. I need to load and store a graph (data) so I need a class (not a function). Some functions which could go in there are fit as functions.

**Comment by kpu** [comment]
> > I hope we are doing something about the redundant abstraction. AbstractTranslationModel can be merged with TranslationModel.
> 
> @abhi-agg wants multiple translators integration capability. My understanding is this means more than marian (maybe another CPP translator/whatever). Rename TranslationModel -> MarianIntegrationModel : AbstractTranslationModel and the existence could be justified, I guess.

Model loading from bytes removes all pretense of being decoder independent and I told Mozilla that.  A decoder-independent interface design can only be tested properly if two decoders are being integrated.  Otherwise we're just gallivanting overengineers and should stop this now.

**Comment by XapaJIaMnu** [comment]
@andrenatal @abhi-agg an example of how to load a binary model through a byte array can be found here for the bergamot version of the app:
https://github.com/browsermt/bergamot-translator/blob/5a267e05885a3d2132663d286b14b4a5b95f549d/app/bergamot-translator-app-bytearray.cpp#L26

And here for the marian-translation-service version of the app:
https://github.com/browsermt/bergamot-translator/blob/5a267e05885a3d2132663d286b14b4a5b95f549d/app/service-cli-bytearray.cpp#L18

It requires this branch of marian which does some small fixes for loading intgemm models: https://github.com/browsermt/marian-dev/tree/binaryload_enable

Now the current functionality does not reduce the memory usage from the old approach. If you want the translator app to re-use the byte array memory that has been provided, you need to also change the binary format to SSSE3 only, as shown in this pull request. (And that would also mean regenerating all binary files that we distribute). What is the call?

**Comment by kpu** [comment]
Check for alignment and die if it doesn't.
