### ISSUE TITLE
Remove Histories from Response

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#53]
Moving from https://github.com/browsermt/bergamot-translator/issues/50.

Given alignments and quality-scores have been extracted in https://github.com/browsermt/bergamot-translator/pull/46, there is potentially no further use for keeping histories_. (@kpu let know if we need anything more from histories) This allows removing histories_, any lazy constructions I was keen on keeping before and the remaining data-members are not strictly marian internal anymore.  

This could pave way for replacing TranslationResult (and thus not having two translation results) mentioned in #50.  However, TranslationResult remains constrained by WASM limitations (like https://github.com/mozilla/bergamot-translator-old/issues/14), which I'm not sure if we want Response to be constrained by as well. Response is the intended output struct for marian-server replacement. 

Assigning task to self.

/cc @kpu, please advise on the WASM situation with TranslationResult.

**Comment by kpu** [comment]
I'm happy about the removal of Histories and collapse of result objects!  

Until they respond to https://github.com/mozilla/bergamot-translator-old/issues/14 just use absl::string_view for the time being.

**Comment by jerinphilip** [comment]
Given they've responded, and above commit for #46 is in, part of solving this issue is covered.

Skeleton of remaining work:

- [ ] Move construction logic of `Response` outside (to maybe a Factory) to be triggered when `Request` completes. `Response` can after be reduced to a `struct`, just carrying data: source, target and respective annotations, Quality and Alignments. This will remove `vocabs`, and `histories_` dependency in `Response` constructor.  
- [ ] Not having `histories_` will break functionality at replacement-decoder for benchmarks and running speed tests. Adjust the marian-decoder replacements to consume processed from history data (translation + annotation). Remove `OutputCollector` dependency. 

Probably after this, there is nothing offending in Response class (no vocabs, no histories) to be even directly exported to WASM (through bindings). The removal of histories and moving construction out make Response equivalent to (desired) TranslationResult.
