### ISSUE TITLE
Consensus on a style guideline with supported tooling

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#54]
There is really no fixed style guideline for bergamot-translator. I'm using [vim-codefmt](https://github.com/google/vim-codefmt) to get something consistent adhering to clang-format. [google/styleguide](https://google.github.io/styleguide/cppguide.html) as much as possible. Since the majority of the code adheres to this, I propose to make this standard. 

Also no java style setters and getters please, if possible? Can we get rid of the header files with camel-case names as well? 

It's getting a bit inconsistent among all of us, might be convenient to get this sorted.

/cc @kpu @abhi-agg

**Comment by jerinphilip** [comment]
Can we get this resolved fast over discussion, at least before the shortlist PR (https://github.com/browsermt/marian-dev/pull/26)? 


My latest changes seem to be invading places where it shouldn't be - https://github.com/browsermt/bergamot-translator/commit/24508208c8a8cedef31f70f3f709580c257c77a4.

**Comment by kpu** [comment]
This is C++ not java.  For better or worse, we should follow what Marian looks like.   snakeCase when Marian does.  Use _ at the end of member variable.

**Comment by abhi-agg** [comment]
@kpu @jerinphilip Marian uses this:

1. Name of the classes/struct like [ConfigParser](https://github.com/browsermt/marian-dev/blob/master/src/common/config_parser.h#L37)
2. Class/struct member functions like [addOptions()](https://github.com/browsermt/marian-dev/blob/master/src/common/config_parser.h#L49)
3. Name of the files as [config_parser.h](https://github.com/browsermt/marian-dev/blob/master/src/common/config_parser.h)
4. Class/struct data members as [cli_](https://github.com/browsermt/marian-dev/blob/master/src/common/config_parser.h#L107)

So, we can follow this.
(Marian doesn't use [snake case naming style](https://en.wikipedia.org/wiki/Snake_case) if wikipedia is correct).

**Comment by kpu** [comment]
Oh you're right :face_with_head_bandage: I had snake case wrong.  

Fine point:
If it's a private member variable lineNo_;
If it's a public struct member variable, lineNo;
