### ISSUE TITLE
Binary shortlist loading from bytebuffer

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#58]
@qianqianzhu You're supposed to follow @XapaJIaMnu's PR for model loading as a byte array (https://github.com/browsermt/bergamot-translator/pull/55), to provide the bytebuffer for shortlist (instead of model) as an argument at 5 places (or less). This would be `shortlist_memory` instead of `model_memory`. 

Whether you build against main or Nick's PR is upto you, if it were up to me I'd do it on top of Nick's PR and create a mess. Note that since both of you are editing at the same places to pass the bytearray, expect a (simple to fix) conflict which one of you will have to deal with depending on who gets their code into main first.

The shortlist loading happens here: https://github.com/browsermt/bergamot-translator/blob/f89c989b444841afd7458df97152ac1401f23750/src/translator/batch_translator.cpp#L21

All translation is dumped into the `BatchTranslator` abstraction (where the shorlist is loaded), with `Service` delegating the query to BatchTranslator to translator after preprocessing and getting the input ready as a batch. Due to bergamot's insistence of a bridge interface to potentially integrate multiple translators, you'll have to pass the `const void * ` (as argument) through:

`AbstractTranslationModel` -> `TranslationModel` -> `NonThreadedService` ->  `BatchTranslator` , [`ServiceBase`].  [] means optional, like Nick did.

I'd be grateful if you adjust it at `Service` as well, which is the multithreaded implementation. If too much, I'm competent enough to do it on my own once the remaining are ready. Advance apologies for this mess.

**Comment by kpu** [comment]
Stop creating more of a mess.  Get Nick's PR in.

**Comment by qianqianzhu** [comment]
@jerinphilip Can you first get https://github.com/browsermt/marian-dev/pull/26 merged? Then I can have the new `BinaryShortlistGenerator` to make changes.

**Comment by kpu** [comment]
Merge into browsermt/marian-dev#26 done.  I've demanded @jerinphilip simplify Service (#61) to decrease the tax imposed by too many classes.

**Comment by jerinphilip** [comment]
Hello @qianqianzhu. Your scope ends at demonstrating functionality at the boundary of `Service`, which is now collapsed into a single class with ifdefs. 

Probably keep a watch on how https://github.com/browsermt/bergamot-translator/issues/63 moves, as you'll need similar datatypes for shortlist as well?

Service handles interaction of translation components.

https://github.com/browsermt/bergamot-translator/blob/34228d37bfcc44e36bf01d8ea70fbc2fce9d9ae9/src/translator/service.h#L43.

You will have to get the shortlist memory down to batchtranslator through: 
https://github.com/browsermt/bergamot-translator/blob/34228d37bfcc44e36bf01d8ea70fbc2fce9d9ae9/src/translator/service.cpp#L57

https://github.com/browsermt/bergamot-translator/blob/34228d37bfcc44e36bf01d8ea70fbc2fce9d9ae9/src/translator/batch_translator.h#L36

BatchTranslator will look like translator or server parts which you already have edited to bring the changes to marian-dev.

To test functionality, please follow @XapaJIaMnu on https://github.com/browsermt/bergamot-translator/pull/55, but do not edit the unified API boundaries (TranslationModel, AbstractTranslationModel) as it can potentially lead to WASM build errors etc. You might just want to incorporate the bytearray shortlist test just below:

https://github.com/browsermt/bergamot-translator/blob/34228d37bfcc44e36bf01d8ea70fbc2fce9d9ae9/app/service-cli-bytearray.cpp#L18

**Comment by qianqianzhu** [comment]
Just made a new PR (https://github.com/browsermt/marian-dev/pull/28#issue-599540382) to enable binary shortlist loading from bytebuffer (which was missed last time). Also, if this PR get merged, can we update marian-dev submodule?

**Comment by jerinphilip** [comment]
@qianqianzhu Looks like kpu seems to be squash merging small features. 

> can we update marian-dev submodule? 

This needn't block your feature development. Get the functionality (in bergamot-translator) ready within your PR by change of submodule (you can change the submodule as you want in shortlist_plumb branch) and bring that in with your PR? Given the squash merges, multiple jumps aren't likely to pollute history.

(There's a mess in marian-dev submodules due to some wasm divergence, ideally don't bother, just develop your functionality, nothing till Service should be affected).

**Comment by qianqianzhu** [comment]
Thanks! If this is fine to make changes, I will make a PR soon.

**Comment by abhi-agg** [comment]
@qianqianzhu Can we close this issue or is there anything else that is left to be done before closing it?

**Comment by kpu** [comment]
@abhi-agg From our perspective it's ready for javascript to give us the bytes.
