### ISSUE TITLE
Adjust WASM (bindings) side of bytebuffer loads

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#59]
Model and shortlist byte array loads are being prepared. However, these are untested on the WASM side of integration in this repo. Particularly, that of `TranslationModel`, where only the string based constructor and not the const void* based constructor is being exported.

https://github.com/browsermt/bergamot-translator/blob/f89c989b444841afd7458df97152ac1401f23750/wasm/bindings/TranslationModelBindings.cpp#L14-L23

**Comment by abhi-agg** [comment]
Closing as it is duplicate of https://github.com/browsermt/bergamot-translator/issues/75

**Comment by abhi-agg** [comment]
Closing this one as it is duplicate of https://github.com/browsermt/bergamot-translator/issues/75
