### ISSUE TITLE
Pass size of model data

### ISSUE THREAD

**Issue by kpu** [browsermt/bergamot-translator#63]
We can't just pass a void * for the model data.  There needs to be some validation that the size allocated by the client is consistent with the size encoded in the model.

**Comment by jerinphilip** [comment]
Does it make sense to abstract the datatype here `(const void *data, size_t size)` and reuse it for shortlist as well? I found the following in https://github.com/browsermt/bergamot-translator/issues/28#issuecomment-780177578.

```cpp
class MemoryGift {
  const char *data() const;
  size_t length() const;
  void early_free();
};
```

Does it make sense to bundle these for model, shortlist (seeing as to someone who'd use bytearray uses it for efficiency purposes) and unpack it at BatchTranslator (where these are loaded)? Vocabulary I'm not sure, but it's required at service as well.

**Comment by abhi-agg** [comment]
@XapaJIaMnu Can we close this issue? I think https://github.com/browsermt/bergamot-translator/pull/94 was the last missing PR to close this one. Right?
