### ISSUE TITLE
Make marian-decoder-new consume Response instead of Histories

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#66]
#53, #65 requires this as a prerequisite.

Not having `histories_` will break functionality at replacement-decoder for benchmarks and running speed tests. Adjust the marian-decoder replacements to consume processed from history data (translation + annotation). Remove `OutputCollector` dependency. The process can also get rid of the lineNumber information when streamed from a large corpus, which we do not need in a request response mode of operation.

**Comment by jerinphilip** [comment]
@eu9ene Moving discussion to relevant issue.

> My observations:
> 
> wmt20 en, number of lines 1418
> Line 224:
> ```
> As inflation climbs and the cost of living in Oregon soars, these workers are being left to flounder, and management has shown little sympathy for their plight. Contract negotiations that began in February broke down in mid-August. At that point, the bosses had laid out some particularly egregious proposals - a paltry cost-of-living increase, a denial of seniority demands from long-term university workers, and a price hike for staff meals - that workers saw as disrespectful, and even cruel. "There is an unwritten class system at the universities," Fulmer said. "And we are at the bottom of it."
> ```
> 
> My app, number of lines in `de` output 1418 ( `--ssplit-mode` option is not specified)
> Line 224:
> ```
> Während die Inflation steigt und die Lebenshaltungskosten in Oregon in die Höhe klettern, werden diese Arbeiter ins Wunkeln gelassen, und das Management hat wenig Verständnis für ihre Notlage gezeigt. Die im Februar begonnenen Vertragsverhandlungen scheiterten Mitte August. Zu diesem Zeitpunkt hatten die Chefs einige besonders ungeheuerliche Vorschläge vorgelegt - eine dürftige Erhöhung der Lebenshaltungskosten, eine Leugnung der Dienstaltersanforderungen von langjährigen Universitätsarbeitern und eine Preiserhöhung für die Mahlzeiten des Personals - die Arbeiter als respektlos und sogar grausam ansahen. "Es gibt ein ungeschriebenes Klassensystem an den Universitäten", sagte Fulmer. "Und wir sind am unteren Ende".
> ```
> 
> 
> `marian-decode-new`, number of lines in output with `--ssplit-mode sentence` 1428
> Line 224 and 225 (unexpected new line break)
> ```
> Während die Inflation steigt und die Lebenshaltungskosten in Oregon in die Höhe schießen, werden diese Arbeiter ins Wanken gelassen, und das Management hat wenig Verständnis für ihre Notlage gezeigt. Die Vertragsverhandlungen, die im Februar begannen, scheiterten Mitte August. Zu diesem Zeitpunkt hatten die Bosse einige besonders ungeheuerliche Vorschläge aufgestellt - eine dürftige Erhöhung der Lebenshaltungskosten, eine Verweigerung der Dienstaltersanforderungen von langjährigen Universitätsarbeitern und eine Preiserhöhung für Personalprämien - das Arbeiter als respektlos und sogar grausam an den Universitäten sahen.
> "Bedermer sagte: "Und wir sind am unteren Ende".
> ```
> 
> `marian-decode-new`, number of lines in output with `--ssplit-mode paragraph` 2103
> 
> 
> So, a number of output lines for `marian-decoder-new` does not match a number of input lines which makes it not usable for evaluation pipelines. Maybe I do something wrong?
> Also translations are a bit different for my app and `marian-decoder-new` which is likely a side effect of incorrect splitting.

**Comment by jerinphilip** [comment]
@eu9ene:

This is an intermediate we should fix. Try `--max-length-break <big-value>`  for now (you can see this is happening on long sentences) and see if problem persists. `--ssplit-mode sentence` is expected. 

(Background: sentence splitting API breaks sentences, the code which puts it back is not integrated yet, `marian-decoder-new` will work okay when this issue is sorted without `--max-length-break` troubles. However, this will have effects on BLEU, always leave it bigger than the largest sentence in test-set for ideal evaluations).

**Comment by eu9ene** [comment]
Those are arguments I used before (exactly the same as we use in the extension)

```
ARGS=(
    -m $MODEL_DIR/$MODEL
    --vocabs
        $MODEL_DIR/$VOCAB # source-vocabulary
        $MODEL_DIR/$VOCAB # target-vocabulary
    --beam-size 1
    --normalize 1.0
    --word-penalty 0
    --max-length-break 128
    --mini-batch-words 1024
    --workspace 128
    --max-length-factor 2.0
    --skip-cost
    --cpu-threads 0
    --quiet
    --quiet-translation
    --shortlist $MODEL_DIR/lex.$SRC$TRG.s2t 50 50
#    --ssplit-mode paragraph
)
```

Replacing values above with `--max-length-break 1000  --ssplit-mode sentence`, `marian-decoder-new` produces correct number of output lines, but translation and BLEU scores are different from using `TranslationModel` with default `--ssplit-mode`.

Using `--max-length-break 1000 --ssplit-mode paragraph`, `marian-decoder-new` doesn't not produce correct number of lines. I would expect this option to work because wmt20 en-de lines are essentially paragraphs composed of multiple sentences.

**Comment by jerinphilip** [comment]
I will try to understand more the requirements here.

1. You want to simply report the quality of the underlying system (in which case you do `--ssplit-mode sentence`). 
2. You want to know the quality after the browser extension efficiency stuff (sentence-breaks etc) are imposed. This is perhaps desirable for the extension to report true to outside BLEU scores. In which case, I'll suggest the following implementation.

**Faithful to source string translation**: This is where I place the translated-sentences as they were in the source, replacing the corresponding source sentences. How I will accomplish this is I have the reference string, and I have the `ByteRanges` of sentences (and consequently boundaries outside). Similar to how it's done over [here](https://github.com/ugermann/ssplit-cpp/blob/master/src/command/test_ssplit.cpp). 

@eu9ene Does the above work? Since WMT sentences are placed back similar to source, the newlines untouched by the process, structure should replicate and cover your use-case, where you want paragraphs to be faithful to source translated.

I'll also /cc @kpu for comments, as there was some confusion when I first brought this up regarding whether this is ideal, as languages have different boundaries for sentences (not just spaces, or imitating source structure and it's space equivalents). 

1. I can do this during construction which makes it immediately available at bergamot-translator-app through `getTranslatedText` (this means consistency with regards to both `marian-decoder-new` and `bergamot-translator-app`). In ResponseBuilder with this case we are doing it at https://github.com/browsermt/bergamot-translator/issues/65.
2. Just change how `marian-decoder-new` works, I can also move this code into decoder and keep sentences together with space.
