### ISSUE TITLE
Update marian-dev submodule to use its master branch

### ISSUE THREAD

**Issue by abhi-agg** [browsermt/bergamot-translator#70]
Currently, the marian-dev submodule of this repository links to [wasm branch of marian-dev](https://github.com/browsermt/marian-dev/tree/wasm)

Change it back to `master` branch.

**Comment by jerinphilip** [comment]
Are you on this @abhi-agg? I can couple this a workflow file rearrangement now that are no master / wasm differences.

**Comment by abhi-agg** [comment]
I can do this but @XapaJIaMnu 's [PR](https://github.com/browsermt/marian-dev/pull/27) should be merged to marian-dev master before we make this switch. Otherwise, things will not work.

@XapaJIaMnu Could you please merge your change to browsermt/marian-dev's master? We can start this task as soon as you merge it.
