### ISSUE TITLE
Adapt JS bindings for WASM module to pass files as byte array from browser extension

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#75]
Current bindings only support the single `std::string` config constructor. The adjustment which succeeds at least in builds in the WASM - `TranslationModel` boundary needn't wait until the feature is developed in marian end to speed things up. Ideally, this part should be testable using stubs so that we know that if something fails we are to look in marian or the WASM boundary.

https://github.com/mozilla/bergamot-translator/issues/8 complains about `std::string_view` exports (which I hope is just absence of first class support) while conceptually a `string_view` is only `const void* + size_t`. If you need to test with the actual pointer, @XapaJIaMnu has already gotten it till WASM-TranslationModel boundary (https://github.com/browsermt/bergamot-translator/pull/55/commits/7da6392013cfc69bf87b5aa51da93a5daa995fcb) with the model in current main.

https://github.com/browsermt/bergamot-translator/blob/e0dca1ba1b5d345a1c81a8932addd711f37b51c7/wasm/bindings/TranslationModelBindings.cpp#L14-L22

> Refactoring const void *model_memory, size_t model_memory_size with a MemoryGift struct or something can be done later once I generate JS bindings.

Please prioritize this and bring this asap so #69 gets timely feedback.

EDIT: Files in question here are model, vocabulary and shortlist files.

**Comment by XapaJIaMnu** [comment]
So what i'm thinking is having something like
```c++
class marian_model {
   explicit marian_model(void * model_bytes, size_t model_bytes_size, void * shortlist, size_t shortlist_size,  void * vocab, size_t vocab size) {
                 validate_model_integrity();
                 validate_vocab_integrity();
                 validate_shortlist_integrity();
                 }
    marian_model() = delete;
```
Maybe include the config to it as well, and do a sanity-check that all the files are correct. Or use checksums for validation..

**Comment by kpu** [comment]
I think you meant const void *

**Comment by abhi-agg** [comment]
@jerinphilip There is another issue in this repo https://github.com/browsermt/bergamot-translator/issues/59 that you created and sounds similar to me. I am closing that one.

**Comment by abhi-agg** [comment]
- [x] Write bindings for AlignedMemory class
- [x] Adapt bindings of TranslationModel class to use AlignedMemory for passing model and shortlist bytes
- [x] Modify wasm test page to:
    - [x] Load both model and shortlist file from local machine (instead of emscripten’s emulated file system)
    - [x] Read these files into bufferr and populate AlignedMemory instances with them
    - [x] Provide these AlignedMemory instances while constructing TranslationModel object
    - [x] Change config string appropriately (remove model and shortlist entry from it) 
- [x] Test whether both model and shortlist files are successfully being passed as bytes from wasm test page
- [x] Test from wasm test page whether it performs inference
    - [x] Test for at least 1 direction (e.g. ES->EN)

**Comment by abhi-agg** [comment]
- [ ] Perform all [tasks](https://github.com/browsermt/bergamot-translator/issues/75#issuecomment-829090647) for passing **vocabulary files** as bytes as well
