### ISSUE TITLE
Build of bergamot-translator-regression-tests on jenkins@vali are failing

### ISSUE THREAD

**Issue by marianminion** [browsermt/bergamot-translator#84]
marion-minion @ jenkins on vali: Build bergamot-translator-regression-tests build failed.

View full output [here](http://vali.inf.ed.ac.uk/jenkins/job/bergamot-translator-regression-tests/56/).

<details> <summary> Click here to expand last 50 lines of build output </summary>
<p>

```
$(OUTPUT, lines=50)
```

</p>
</details>

**Comment by jerinphilip** [comment]
Fixed by #91, well sort-of.
